### PR TITLE
Fix permalinks of titles containing ticks

### LINKED ISSUE #45: Issue with <code> elements in headings
This file: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/dashboard.rst has things like these:

```rst
The ``Admin`` list block
------------------------

Configuring the ``Admin`` list
------------------------------

Using the ``Admin`` service declaration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

These are wrongly processed in the TOC, which shows the links like this:

image

The contents of the heading are correctly displayed, but the "weird alphanumeric string" leaks to the permalink too:

image

### PR DESCRIPTION
**Pull request by nikophil**
Hello, 

this fixes https://github.com/weaverryan/docs-builder/pull/45

The problem is related to what @weaverryan fixed here https://github.com/doctrine/rst-parser/pull/124

We actually need a way to access to the "real text" of the `SpanNode` from both `DocumentNode` and `TitleNode`, thus I've moved the logic into `SpanNode` with help of `SpanProcessor`. I've simplified a bit Ryan's `DocumentNode::getTextFromNode()` but no problem to take back his version if we think it's more efficient.

### CODE REVIEW

**Comment by greg0ire** [comment]
:thinking: I don't think there are any forgotten PRs in 0.2.x, IMO what you want to target is 1.0.x

**Comment by greg0ire** [comment]
Actually, you should rebase on 0.3.x.

**Comment by greg0ire** [comment]
I think you might want to drop @weaverryan 's commits, as I probably had similar work to do on 0.3.x

File: lib/Nodes/SpanNode.php [hunk 1]
```diff
@@ -17,6 +17,9 @@ class SpanNode extends Node
     /** @var string */
     protected $value;
 
+    /** @var string */
+    protected $text;
```
Comment (greg0ire) [inline lib/Nodes/SpanNode.php]: I don't think there is a reason for this to be protected.

```suggestion
    private $text;
```

Maybe we should make a lot of properties in this project private as well before releasing 1.0.0

Comment (nikophil) [reply lib/Nodes/SpanNode.php]: indeed you're right, fixed

**Review by javiereguiluz — APPROVED** [review]
Nice one Nicolas!

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @nikophil !
